{{- if include "hermes-ai-assistant.createSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hermes-ai-assistant.fullname" . }}
  labels:
    {{- include "hermes-ai-assistant.labels" . | nindent 4 }}
type: Opaque
data:
  {{- include "hermes-ai-assistant.secretData" . | nindent 2 }}
{{- end }}