apiVersion: v1
kind: Service
metadata:
  name: {{ include "hermes-ai-assistant.fullname" . }}
  labels:
    {{- include "hermes-ai-assistant.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
      {{- if .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    {{- include "hermes-ai-assistant.selectorLabels" . | nindent 4 }}